# Numpy Library
## Numpy Basic

In [2]:
#Getting Started:
#Import NumPy
import numpy

In [5]:
#Ex.
import numpy
array = numpy.array([8,4,3,1,5,7])
print(array)

[8 4 3 1 5 7]


In [4]:
#NumPy as np:
import numpy as np
array = np.array([8,4,3,1,5,7])
print(array)

[8 4 3 1 5 7]


In [6]:
#Creating Arrays:
#create a NumPy ndarray object by using the array() function
import numpy as np
array = np.array([8,4,3,1,5,7])
print(type(array))

<class 'numpy.ndarray'>


In [8]:
#Dimensions in Arrays:
#Create a 0-D array 
import numpy as np
array = np.array(25)
print(array)

25


In [9]:
#Create a 1-D array 
import numpy as np
array = np.array([8,4,3,1,5,7])
print(array)

[8 4 3 1 5 7]


In [10]:
#Create a 2-D array
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [11]:
#Create a 3-D array 
import numpy as np
array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
#Array Indexing or Access Array Elements:
#Get the first element from the array
import numpy as np
array = np.array([8,4,3,1,5,7])
print(array[0])

8


In [13]:
#Get third and fourth elements from the array 
import numpy as np
array = np.array([8,4,3,1,5,7])
print(array[2] + array[3])

4


In [14]:
#Access the element on the first row, second column
import numpy as np
array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', array[0, 1])

2nd element on 1st row:  2


In [15]:
#Access the third element of the second array of the first array
import numpy as np
array = np.array([[[4, 2, 3], [4, 5, 7]], [[7, 8, 9], [10, 11, 12]]])
print(array[0, 1, 2])

7


In [16]:
#Print the last element from the 2nd dim
import numpy as np
array = np.array([[7,2,3,4,5], [6,7,8,9,5]])
print('Last element from 2nd dim: ', array[1, -1])

Last element from 2nd dim:  5


In [17]:
#Array Slicing:
#Slice elements from index 1 to index 5 from the array
import numpy as np
array = np.array([8, 5, 3, 7, 5, 2, 4])
print(array[1:5])

[5 3 7 5]


In [18]:
#Slice from the index 3 from the end to index 1 from the end
import numpy as np
array = np.array([8, 5, 3, 7, 5, 2, 4])
print(array[-6:-2])

[5 3 7 5]


In [22]:
#Return every other element from index 1 to index 5:
import numpy as np
array = np.array([8, 5, 3, 7, 5, 2, 4])
print(array[2:5:1])

[3 7 5]


In [23]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np
array = np.array([[7, 2, 8, 4, 10], [3, 7, 6, 9, 1]])
print(array[0:3, 2:5])

[[ 8  4 10]
 [ 6  9  1]]


In [24]:
#Data Types:
#Checking the Data Type of an Array
import numpy as np
array = np.array([1, 2, 3, 4])
print(array.dtype)

int32


In [25]:
import numpy as np
array = np.array(['mango', 'banana', 'orange'])
print(array.dtype)

<U6


In [29]:
#Creating Arrays With a Defined Data Type
import numpy as np
array = np.array([1, 2, 3, 4], dtype='S')
print(array)
print(array.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [30]:
#Change data type from integer to boolean:
import numpy as np
array = np.array([1, 0, 3])
newarray = array.astype(bool)
print(newarray)
print(newarray.dtype)

[ True False  True]
bool


In [31]:
#Array Copy vs View:
#Make a copy, change the original array, and display both arrays:
import numpy as np
array = np.array([5, 2, 8, 4, 6])
x = array.copy()
array[1] = 25
print(array)
print(x)

[ 5 25  8  4  6]
[5 2 8 4 6]


In [32]:
#Make a view, change the original array, and display both arrays:
import numpy as np
array = np.array([5, 2, 8, 4, 6])
x = array.view()
array[3] = 18
print(array)
print(x)

[ 5  2  8 18  6]
[ 5  2  8 18  6]


In [33]:
#Print the value of the base attribute to check if an array owns it's data or not:
import numpy as np
array = np.array([5, 2, 8, 4, 6])
a = array.copy()
b = array.view()
print(a.base)
print(b.base)

None
[5 2 8 4 6]


In [34]:
#Array Shape:
#Print the shape of a 2-D array
import numpy as np
array = np.array([[1, 2, 3, 4,5], [5, 6, 7, 8,9]])
print(array.shape)

(2, 5)


In [38]:
#Create an array with 5 dimensions using ndmin 
import numpy as np
array = np.array([5, 6, 7, 8,9], ndmin=5)
print(array)
print('shape of array :', array.shape)

[[[[[5 6 7 8 9]]]]]
shape of array : (1, 1, 1, 1, 5)


In [40]:
#Array Reshaping:
#Reshape From 1-D to 2-D
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
#Check if the returned array is a copy or a view
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [44]:
#converting a multidimensional array into a 1D array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-2)
print(newarr)

[1 2 3 4 5 6]


In [46]:
#Array Iterating:
#Iterate on the elements of the following 1-D array
import numpy as np
arr = np.array([4, 2, 3])
for x in arr:
    print(x)

4
2
3


In [47]:
#Iterating Arrays Using nditer()
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [49]:
#Iterate through the array as a string
import numpy as np
arr = np.array([5, 4, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'5'
b'4'
b'3'


In [50]:
#Iterating With Different Step Size(Iterate through every scalar element of the 2D array skipping 1 element)
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [51]:
#Enumerated Iteration Using ndenumerate() on following 2D array's elements
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [52]:
#Joining Array:
#Join two arrays
import numpy as np
arr1 = np.array([9, 8, 7])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[9 8 7 4 5 6]


In [55]:
#Joining Arrays Using Stack Functions
import numpy as np
arr1 = np.array([9, 8, 7])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2),axis=1)
print(arr)

[[9 4]
 [8 5]
 [7 6]]


In [56]:
#Stacking Along Rows
import numpy as np
arr1 = np.array([9, 8, 7])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[9 8 7 4 5 6]


In [57]:
#Stacking Along Columns
import numpy as np
arr1 = np.array([9, 8, 7])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[9 8 7]
 [4 5 6]]


In [58]:
#Stacking Along Height (depth)
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [60]:
#Splitting Array:
#Split the array in 2
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [63]:
#Access the splitted arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr[0])
print(newarr[1])

[1 2 3]
[4 5 6]


In [64]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [67]:
#Searching Arrays:
#Find the indexes where the value is 4
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 6])
x = np.where(arr == 4)
print(x)

(array([3, 5], dtype=int64),)


In [68]:
#Find the indexes where the values are even
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [69]:
#Find the indexes where the values 2, 4, and 6 should be inserted
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [70]:
#Sorting Arrays:
#Sort the array:
import numpy as np
arr = np.array([4,8,2,9,3])
print(np.sort(arr))

[2 3 4 8 9]


In [73]:
#Sort a boolean array
import numpy as np
arr = np.array([False, False, True,False])
print(np.sort(arr))

[False False False  True]


In [74]:
#Sort a 2-D array
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [75]:
#Filter Array:
#Create an array from the elements on index 0 and 2
import numpy as np
arr = np.array([18,25,11,58])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[18 11]


In [76]:
#Create a filter array that will return only values higher than 42
import numpy as np
arr = np.array([41, 42, 43, 44,45,46])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 44:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, False, False, True, True]
[45 46]


In [77]:
#Create a filter array that will return only even elements from the original array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True]
[2 4 6]
