## Numpy ufunc

In [2]:
#Introduction: ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

In [3]:
#Without ufunc, we can use Python's built-in zip() method
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []
for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [4]:
#With ufunc, we can use the add() function
import numpy as np
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)
print(z)

[ 5  7  9 11]


In [5]:
#Create Your Own ufunc:

In [6]:
#Create your own ufunc for addition
import numpy as np
def myadd(x, y):
  return x+y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [7]:
#Check the type of another function: concatenate()
import numpy as np
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [8]:
#Use an if statement to check if the function is a ufunc or not
import numpy as np
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [9]:
#Simple Arithmetic:

In [10]:
#Add the values in arr1 to the values in arr2
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [11]:
#Subtract the values in arr2 from the values in arr1
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)
print(newarr)

[-10  -1   8  17  26  35]


In [12]:
#Rounding Decimals:

In [13]:
#Truncate elements of following array
import numpy as np
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [14]:
#using fix()
import numpy as np
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [15]:
#Round off 3.1666 to 2 decimal places
import numpy as np
arr = np.around(3.1666, 2)
print(arr)

3.17


In [16]:
#Floor the elements of array
import numpy as np
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [17]:
#Ceil the elements of following array
import numpy as np
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


In [1]:
#Logs:

In [3]:
#Find log at base 2 of all elements of array
import numpy as np
arr = np.arange(5, 15)
print(np.log2(arr))

[2.32192809 2.5849625  2.80735492 3.         3.169925   3.32192809
 3.45943162 3.5849625  3.70043972 3.80735492]


In [5]:
#Find log at base 10 of all elements of array
import numpy as np
arr = np.arange(2, 20)
print(np.log10(arr))

[0.30103    0.47712125 0.60205999 0.69897    0.77815125 0.84509804
 0.90308999 0.95424251 1.         1.04139269 1.07918125 1.11394335
 1.14612804 1.17609126 1.20411998 1.23044892 1.25527251 1.2787536 ]


In [6]:
#Find log at base e of all elements of following array
import numpy as np
arr = np.arange(2, 20)
print(np.log(arr))

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665 2.56494936
 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176 2.94443898]


In [9]:
#Log at Any Base
from math import log
import numpy as np
nplog = np.frompyfunc(log, 2, 1)
print(nplog(200, 10))

2.301029995663981


In [10]:
#Summations:

In [11]:
#Add the values in arr1 to the values in arr2
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.add(arr1, arr2)
print(newarr)

[2 4 6]


In [12]:
#Sum the values in arr1 and the values in arr2
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


In [15]:
#Perform summation in the array over 1st axis
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

[6 6]


In [16]:
#Perform cummulative summation in the following array
import numpy as np
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


In [17]:
#Products:

In [18]:
#Find the product of the elements of this array
import numpy as np
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


In [19]:
#Find the product of the elements of two arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

40320


In [21]:
#Perform summation in the array over 1st axis
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

[  24 1680]


In [22]:
#Cummulative product of all elements for array
import numpy as np
arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


In [23]:
#Differences:

In [24]:
#Compute discrete difference of the array
import numpy as np
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [28]:
#Compute discrete difference of the array twice
import numpy as np
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)
print(newarr)

[  5 -30]


In [29]:
#LCM (Lowest Common Multiple)

In [37]:
#Find the LCM of the two numbers
import numpy as np
num1 = 3
num2 = 6
x = np.lcm(num1, num2)
print(x)

6


In [38]:
#Find the LCM of the values of the array
import numpy as np
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


In [39]:
#Find the LCM of all values of an array where the array contains all integers from 1 to 10
import numpy as np
arr = np.arange(1, 10)
x = np.lcm.reduce(arr)
print(x)

2520


In [40]:
#GCD (Greatest Common Denominator)

In [41]:
#Find the HCF of the two numbers
import numpy as np
num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print(x)

3


In [42]:
#Find the GCD for all of the numbers in the array
import numpy as np
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x):

4


In [43]:
#Trigonometric Functions:

In [44]:
#Find sine value of PI/2
import numpy as np
x = np.sin(np.pi/2)
print(x)

1.0


In [45]:
#Find sine values for all of the values in arr
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [46]:
#Convert all of the values in following array arr to radians
import numpy as np
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [47]:
#Convert all of the values in array arr to degrees
import numpy as np
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [51]:
#Find the angle of 1
import numpy as np
x = np.arcsin(1)
print(x)

1.5707963267948966


In [52]:
#Find the angle for all of the sine values in the array
import numpy as np
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [53]:
#Find the hypotenues for 4 base and 3 perpendicular
import numpy as np
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)

5.0


In [54]:
#Hyperbolic Functions:

In [55]:
#Find sinh value of PI/2
import numpy as np
x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [56]:
#Find cosh values for all of the values in array
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [57]:
#Find the angle of 1
import numpy as np
x = np.arcsinh(1)
print(x)

0.881373587019543


In [58]:
#Find the angle for all of the tanh values in array
import numpy as np
arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print(x)

[0.10033535 0.20273255 0.54930614]


In [59]:
#Set Operations:

In [60]:
#Convert array with repeated elements to a set
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [61]:
#Find union of the two set arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


In [64]:
#Find intersection of the two set arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[3 4]


In [65]:
#Find the difference of the set1 from set2
import numpy as np
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

[1 2]


In [68]:
#Find the symmetric difference of the set1 and set2
import numpy as np
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)

[1 2 5 6]
